![](./template-cover.jpg)

# Fetch OneDrive files in Deepnote

This template shows you how to fetch, analyze and visualize files from OneDrive. The easiest way to do this is to share the file to be publicly accessible with a link. We're using this As an example, we're using [this sales pipeline generated with dummy data](https://1drv.ms/x/s!AjP7y6eiYDDSafV7BusEaDHrI0o?e=cL0Fqi). Click "Run notebook" at the top of this window to see it in action.

_Want to fetch your own files?_ Follow the next steps at the end of the notebook 👇

In [ ]:
import pandas as pd
import base64

## Fetch a file from OneDrive

OneDrive allows us to fetch publicly shared files by taking a share URL and passing it to the [`shares_get` OneDrive API](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/shares_get). The function `get_onedrive_download` creates the URL to download any shared file.

In [ ]:
# Convert a share link to a direct download
# See https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/shares_get
def get_onedrive_download(share_link):
    base64_link_bytes = base64.b64encode(bytes(share_link, 'utf-8'))
    base64_link_string = base64_link_bytes.decode('utf-8').replace('/','_').replace('+','-').rstrip("=")
    return f"https://api.onedrive.com/v1.0/shares/u!{base64_link_string}/root/content"

ONEDRIVE_SHARE_LINK = "https://1drv.ms/x/s!AjP7y6eiYDDSafV7BusEaDHrI0o?e=cL0Fqi"

get_onedrive_download(ONEDRIVE_SHARE_LINK)

'https://api.onedrive.com/v1.0/shares/u!aHR0cHM6Ly8xZHJ2Lm1zL3gvcyFBalA3eTZlaVlERFNhZlY3QnVzRWFESHJJMG8_ZT1jTDBGcWk/root/content'

We then use pandas to read the URL into a dataframe directly. Deepnote summarizes and paginates dataframes automatically. You can filter and sort each column to drill into the data.

In [ ]:
df = pd.read_excel(get_onedrive_download(ONEDRIVE_SHARE_LINK))
df

                  Name     Status Priority  Estimated Value
0        Victor Larson     Closed      Low              900
1      Consuela Lowery       Lead   Medium             2500
2       Chanelle Klein   Proposal   Medium             1800
3         Gregg Harper     Closed     High             3500
4         Walter Hobbs       Lead      Low              800
...                ...        ...      ...              ...
1653    Darron Buckley       Lead   Medium             2100
1654  Hunter Robertson     Closed   Medium             1800
1655       Clint Foley     Closed   Medium             1600
1656     Jonathan Best  Qualified   Medium             2200
1657      Emile Kramer  Qualified      Low             1100

[1658 rows x 4 columns]

## Analyze data with SQL

We can run queries against our dataframe using Deepnote's built-in SQL. [You can learn more about SQL blocks on our docs](https://docs.deepnote.com/features/sql-cells).

In [ ]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

filtered_df = _dntk.execute_sql(
  'SELECT \n  "Estimated Value",\n  "Priority",\n  "Status"\nFROM \n  df\nWHERE\n  NOT ("Status" = \'Closed\' OR "Status" = \'Lost\')',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
filtered_df

      Estimated Value Priority       Status
0                2500   Medium         Lead
1                1800   Medium     Proposal
2                 800      Low         Lead
3                1700   Medium         Lead
4                 600      Low    Qualified
...               ...      ...          ...
1048             2200   Medium    Qualified
1049             2200   Medium  Negotiation
1050             2100   Medium         Lead
1051             2200   Medium    Qualified
1052             1100      Low    Qualified

[1053 rows x 3 columns]

## Visualize data

Deepnote can visualize dataframes out-of-the-box. [You can learn more about chart blocks on our docs](https://docs.deepnote.com/features/chart-blocks).

If you want to do something more sophisticated, you can use visualization libraries like [Altair](https://deepnote.com/@allan-campopiano/Altair-42-8dafcd3e-bdad-45e9-b2ab-3572581ed41b) or [Plotly](https://deepnote.com/@deepnote/3D-network-visualisations-using-plotly-a18c5e37-a517-4b27-bfde-1fee94a5760f).

In [ ]:
_dntk.DeepnoteChart(filtered_df, '{"data":{"name":"placeholder"},"mark":{"type":"bar","tooltip":true},"height":220,"$schema":"https://vega.github.io/schema/vega-lite/v4.json","autosize":{"type":"fit"},"encoding":{"x":{"bin":true,"sort":null,"type":"quantitative","field":"Estimated Value","scale":{"type":"linear","zero":false}},"y":{"sort":null,"type":"quantitative","field":"COUNT(*)","scale":{"type":"linear","zero":true},"aggregate":"count"},"color":{"sort":null,"type":"nominal","field":"Priority","scale":{"type":"linear","zero":false}}}}', filters='[]')

alt.Chart(...)

### Next steps

Rather than use our data, you can fetch your own.

1. **Create a share link to your file**. [Follow these instructions](https://support.microsoft.com/en-us/office/create-a-shareable-link-8257f6da-d5db-4207-a654-925644e3f35c) and make sure anyone with the link can at least **read** the file.
1. **Change `ONEDRIVE_SHARE_LINK` to your share link**.
1. **Click the "Run notebook" button at the top of this window**. All of your new code will run from top to bottom.
1. **Share your notebook with your team**. You can even turn your charts [into a shareable dashboard](https://docs.deepnote.com/collaboration/publishing-a-notebook).

_Want to know more about using Deepnote?_ [Check out or docs](https://docs.deepnote.com/).

You can safely delete this block (and any text block) once you're done with it.

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=7c6d212e-b26d-48ca-a3d0-fcd63f888999' target="_blank">
<img alt='Created in deepnote.com' style='display:inline;max-height:16px;margin:0px;margin-right:7.5px;' src='' />
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>